os:
- linux
- osx
language: generic
sudo: required
dist: trusty
osx_image: xcode11
env:
- SWIFT_VERSION=5.1.1
install:
- git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
- export SWIFTENV_ROOT="$HOME/.swiftenv"
- export PATH="$SWIFTENV_ROOT/bin:$PATH"
- eval "$(swiftenv init -)"
- swiftenv install "$SWIFT_VERSION" || true
- swift --version
script:
- swift test
